# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  adapter: postgresql
  encoding: utf8
  pool: 5
  username: ivanchiang
  password:

development:  
  <<: *default
  database: trip_api_development

test:  
  <<: *default
  database: trip_api_test

production:
  adapter: postgresql
  encoding: utf8
  pool: 5
  username: ivanchiang
  password: 
  database: trip_api_production